package com.example.llm61.screens

import androidx.compose.animation.AnimatedVisibility
import androidx.compose.animation.animateContentSize
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.selection.selectable
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.Lightbulb
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.lifecycle.viewmodel.compose.viewModel
import com.example.llm61.data.QuestionBank
import com.example.llm61.data.UserAnswer
import com.example.llm61.network.LlmUiState
import com.example.llm61.viewmodel.QuizViewModel
import com.example.llm61.viewmodel.UserViewModel

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun QuizScreen(
    taskId: String,
    userViewModel: UserViewModel,
    onSubmitClick: () -> Unit,
    onBackClick: () -> Unit
) {
    // QuizViewModel is local to this screen — gets reset when we leave
    val quizViewModel: QuizViewModel = viewModel()

    val task = remember(taskId) { QuestionBank.getTaskForTopic(taskId) }

    var selectedAnswers by remember { mutableStateOf<Map<Int, Int>>(emptyMap()) }

    Scaffold(
        topBar = {
            TopAppBar(
                title = {
                    Column {
                        Text(
                            "✨ Generated by AI",
                            style = MaterialTheme.typography.labelSmall,
                            color = MaterialTheme.colorScheme.primary
                        )
                        Text(
                            "Quiz: ${task.topic}",
                            style = MaterialTheme.typography.titleMedium
                        )
                    }
                },
                navigationIcon = {
                    IconButton(onClick = onBackClick) {
                        Icon(
                            Icons.AutoMirrored.Filled.ArrowBack,
                            contentDescription = "Back"
                        )
                    }
                }
            )
        },
        bottomBar = {
            Surface(shadowElevation = 8.dp) {
                Column(modifier = Modifier.padding(16.dp)) {
                    Text(
                        "${selectedAnswers.size} of ${task.questions.size} answered",
                        style = MaterialTheme.typography.bodySmall,
                        modifier = Modifier.padding(bottom = 8.dp)
                    )
                    Button(
                        onClick = {
                            val answers = task.questions.map { question ->
                                val selectedIdx = selectedAnswers[question.id]
                                UserAnswer(
                                    question = question,
                                    selectedIndex = selectedIdx,
                                    isCorrect = selectedIdx == question.correctAnswerIndex
                                )
                            }
                            userViewModel.submitQuiz(task.topic, answers)
                            onSubmitClick()
                        },
                        colors = ButtonDefaults.buttonColors(
                            containerColor = MaterialTheme.colorScheme.secondary,
                            contentColor = MaterialTheme.colorScheme.onSecondary
                        ),
                        enabled = selectedAnswers.size == task.questions.size,
                        modifier = Modifier.fillMaxWidth()
                    ) {
                        Text("Submit")
                    }
                }
            }
        }
    ) { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
                .padding(16.dp)
                .verticalScroll(rememberScrollState())
        ) {
            Text(
                text = task.description,
                style = MaterialTheme.typography.bodyMedium,
                modifier = Modifier.padding(bottom = 16.dp)
            )

            task.questions.forEachIndexed { index, question ->
                QuestionCard(
                    questionNumber = index + 1,
                    questionText = question.text,
                    options = question.options,
                    selectedIndex = selectedAnswers[question.id],
                    onOptionSelected = { optionIdx ->
                        selectedAnswers = selectedAnswers + (question.id to optionIdx)
                    },
                    // NEW — hint state and callback for this question
                    hintState = quizViewModel.hintStates[question.id] ?: LlmUiState.Idle,
                    onRequestHint = {
                        quizViewModel.requestHint(question.id, question.text, question.options)
                    },
                    onClearHint = { quizViewModel.clearHint(question.id) }
                )
                Spacer(Modifier.height(12.dp))
            }
        }
    }
}

@Composable
private fun QuestionCard(
    questionNumber: Int,
    questionText: String,
    options: List<String>,
    selectedIndex: Int?,
    onOptionSelected: (Int) -> Unit,
    hintState: LlmUiState,
    onRequestHint: () -> Unit,
    onClearHint: () -> Unit
) {
    Card(
        modifier = Modifier
            .fillMaxWidth()
            .animateContentSize()           // smoothly resize when hint expands/collapses
    ) {
        Column(modifier = Modifier.padding(16.dp)) {
            Text(
                text = "$questionNumber. $questionText",
                style = MaterialTheme.typography.titleMedium,
                fontWeight = FontWeight.Bold
            )
            Spacer(Modifier.height(12.dp))

            options.forEachIndexed { idx, optionText ->
                Row(
                    modifier = Modifier
                        .fillMaxWidth()
                        .selectable(
                            selected = (selectedIndex == idx),
                            onClick = { onOptionSelected(idx) }
                        )
                        .padding(vertical = 4.dp),
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    RadioButton(
                        selected = (selectedIndex == idx),
                        onClick = { onOptionSelected(idx) }
                    )
                    Spacer(Modifier.width(8.dp))
                    Text(optionText, style = MaterialTheme.typography.bodyMedium)
                }
            }

            Spacer(Modifier.height(8.dp))
            HorizontalDivider()
            Spacer(Modifier.height(8.dp))

            // ============= NEW: AI Hint Section =============
            HintSection(
                state = hintState,
                onRequestHint = onRequestHint,
                onClearHint = onClearHint
            )
        }
    }
}

@Composable
private fun HintSection(
    state: LlmUiState,
    onRequestHint: () -> Unit,
    onClearHint: () -> Unit
) {
    when (state) {
        // Initial state — show the trigger button
        LlmUiState.Idle -> {
            OutlinedButton(
                onClick = onRequestHint,
                modifier = Modifier.fillMaxWidth()
            ) {
                Icon(
                    Icons.Default.Lightbulb,
                    contentDescription = null,
                    modifier = Modifier.size(18.dp)
                )
                Spacer(Modifier.width(8.dp))
                Text("Get AI Hint")
            }
        }

        // Waiting for response
        LlmUiState.Loading -> {
            Row(
                verticalAlignment = Alignment.CenterVertically,
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(8.dp)
            ) {
                CircularProgressIndicator(
                    modifier = Modifier.size(20.dp),
                    strokeWidth = 2.dp
                )
                Spacer(Modifier.width(12.dp))
                Text(
                    "Generating hint...",
                    style = MaterialTheme.typography.bodyMedium
                )
            }
        }

        // Got a response — show prompt + response (required by assignment)
        is LlmUiState.Success -> {
            AnimatedVisibility(visible = true) {
                Column {
                    PromptAndResponseDisplay(
                        prompt = state.prompt,
                        response = state.response,
                        responseLabel = "💡 AI Hint",
                        responseColor = MaterialTheme.colorScheme.primaryContainer
                    )
                    TextButton(onClick = onClearHint) {
                        Text("Hide hint")
                    }
                }
            }
        }

        // Something went wrong
        is LlmUiState.Error -> {
            Column {
                Card(
                    colors = CardDefaults.cardColors(
                        containerColor = MaterialTheme.colorScheme.errorContainer
                    ),
                    modifier = Modifier.fillMaxWidth()
                ) {
                    Column(modifier = Modifier.padding(12.dp)) {
                        Text(
                            "❌ Couldn't get hint",
                            style = MaterialTheme.typography.titleSmall,
                            fontWeight = FontWeight.Bold
                        )
                        Spacer(Modifier.height(4.dp))
                        Text(
                            state.message,
                            style = MaterialTheme.typography.bodySmall
                        )
                    }
                }
                Spacer(Modifier.height(8.dp))
                OutlinedButton(
                    onClick = onRequestHint,
                    modifier = Modifier.fillMaxWidth()
                ) {
                    Text("Try Again")
                }
            }
        }
    }
}

// Reusable component for showing prompt + response
// We'll reuse this in Phase 7 for the explanation feature
@Composable
fun PromptAndResponseDisplay(
    prompt: String,
    response: String,
    responseLabel: String,
    responseColor: androidx.compose.ui.graphics.Color
) {
    Column(modifier = Modifier.fillMaxWidth()) {
        // Prompt block — collapsed by default to save space
        var promptExpanded by remember { mutableStateOf(false) }

        Card(
            colors = CardDefaults.cardColors(
                containerColor = MaterialTheme.colorScheme.surfaceVariant
            ),
            modifier = Modifier.fillMaxWidth()
        ) {
            Column(modifier = Modifier.padding(8.dp)) {
                Row(
                    verticalAlignment = Alignment.CenterVertically,
                    modifier = Modifier
                        .fillMaxWidth()
                        .selectable(
                            selected = promptExpanded,
                            onClick = { promptExpanded = !promptExpanded }
                        )
                ) {
                    Text(
                        "📝 Prompt sent to AI",
                        style = MaterialTheme.typography.labelSmall,
                        fontWeight = FontWeight.Bold,
                        modifier = Modifier.weight(1f)
                    )
                    Text(
                        if (promptExpanded) "Hide" else "Show",
                        style = MaterialTheme.typography.labelSmall,
                        color = MaterialTheme.colorScheme.primary
                    )
                }
                AnimatedVisibility(visible = promptExpanded) {
                    Text(
                        prompt,
                        style = MaterialTheme.typography.bodySmall,
                        fontStyle = FontStyle.Italic,
                        modifier = Modifier.padding(top = 4.dp)
                    )
                }
            }
        }

        Spacer(Modifier.height(8.dp))

        // Response block — always visible
        Card(
            colors = CardDefaults.cardColors(containerColor = responseColor),
            modifier = Modifier.fillMaxWidth()
        ) {
            Column(modifier = Modifier.padding(12.dp)) {
                Text(
                    responseLabel,
                    style = MaterialTheme.typography.labelMedium,
                    fontWeight = FontWeight.Bold
                )
                Spacer(Modifier.height(4.dp))
                Text(
                    response,
                    style = MaterialTheme.typography.bodyMedium
                )
            }
        }
    }
}